/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eksperyment;

import java.awt.Dimension;
import javax.swing.ButtonGroup;

/**
 *
 * @author Tomasz
 */
public class Okno extends javax.swing.JFrame {

    /**
     * Creates new form Okno
     */
    public Okno() {
        initComponents();
        for (int i = 0; i <= 10000; i++) {
            Eksperyment.aList.add(String.valueOf(i));
            Eksperyment.lList.add(String.valueOf(i));
        }

        info.setText("Wypełniono obie listy liczbami (10 000) \nprzyporządkowanymi względem pozycji w listach.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        arrayButton = new javax.swing.JButton();
        radio1 = new javax.swing.JRadioButton();
        radio2 = new javax.swing.JRadioButton();
        radio3 = new javax.swing.JRadioButton();
        radio4 = new javax.swing.JRadioButton();
        radio5 = new javax.swing.JRadioButton();
        radio6 = new javax.swing.JRadioButton();
        radio7 = new javax.swing.JRadioButton();
        radio8 = new javax.swing.JRadioButton();
        radio9 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        info = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);

        jLabel1.setText("Sprawdź co jest szybsze !");

        arrayButton.setText("Porównaj");
        arrayButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                arrayButtonMousePressed(evt);
            }
        });

        radio1.setText("Początek");

        radio2.setText("Środek");

        radio3.setText("Koniec");

        radio4.setText("Początek");

        radio5.setText("Środek");

        radio6.setText("Koniec");
        radio6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio6ActionPerformed(evt);
            }
        });

        radio7.setText("Początek");

        radio8.setText("Środek");

        radio9.setText("Koniec");
        ButtonGroup grupa = new ButtonGroup();
        grupa.add(radio1);
        grupa.add(radio2);
        grupa.add(radio3);
        grupa.add(radio4);
        grupa.add(radio5);
        grupa.add(radio6);
        grupa.add(radio7);
        grupa.add(radio8);
        grupa.add(radio9);

        jLabel4.setText("Wstawianie:");

        jLabel5.setText("Usuwanie: ");

        jLabel6.setText("Wyświetlanie: ");

        info.setEditable(false);
        info.setColumns(20);
        info.setLineWrap(true);
        info.setRows(5);
        jScrollPane1.setViewportView(info);

        jButton3.setText("Reset");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radio1)
                                .addGap(18, 18, 18)
                                .addComponent(radio2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radio4)
                                .addGap(18, 18, 18)
                                .addComponent(radio5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radio7)
                                .addGap(18, 18, 18)
                                .addComponent(radio8)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radio3)
                            .addComponent(radio9)
                            .addComponent(radio6))
                        .addGap(0, 72, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(arrayButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jButton3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addComponent(arrayButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio1)
                    .addComponent(radio3)
                    .addComponent(radio2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio4)
                    .addComponent(radio6)
                    .addComponent(jLabel5)
                    .addComponent(radio5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio7)
                    .addComponent(radio8)
                    .addComponent(radio9)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void arrayButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrayButtonMousePressed
        long startTime = 0;
        long endTime = 0;
        long resultArray = 0;
        long resultLinked = 0;
        long resultFinal = 0;
        info.setText("");
        if (radio1.isSelected()) {
            startTime = System.nanoTime();
            Eksperyment.aList.add(0, "Początek");
            endTime = System.nanoTime();
            resultArray = endTime - startTime;

            startTime = System.nanoTime();
            Eksperyment.lList.add(0, "Początek");
            endTime = System.nanoTime();
            resultLinked = endTime - startTime;

            info.setText("Dodałem element na początek obu list.");
        }
        if (radio2.isSelected()) {
            startTime = System.nanoTime();
            Eksperyment.aList.add((Eksperyment.aList.size() / 2), "Środek");
            endTime = System.nanoTime();
            resultArray = endTime - startTime;

            startTime = System.nanoTime();
            Eksperyment.lList.add((Eksperyment.lList.size() / 2), "Środek");
            endTime = System.nanoTime();
            resultLinked = endTime - startTime;

            info.setText("Dodałem element w środek obu list.");
        }
        if (radio3.isSelected()) {
            startTime = System.nanoTime();
            Eksperyment.aList.add("Koniec");
            endTime = System.nanoTime();
            resultArray = endTime - startTime;

            startTime = System.nanoTime();
            Eksperyment.lList.add("Koniec");
            endTime = System.nanoTime();
            resultLinked = endTime - startTime;
            info.setText("Dodałem element na koniec obu list.");
        }
        if (radio4.isSelected()) {
            startTime = System.nanoTime();
            Eksperyment.aList.remove(0);
            endTime = System.nanoTime();
            resultArray = endTime - startTime;

            startTime = System.nanoTime();
            Eksperyment.lList.remove(0);
            endTime = System.nanoTime();
            resultLinked = endTime - startTime;
            info.setText("Usunołem element z początku obu list.");
        }
        if (radio5.isSelected()) {
            startTime = System.nanoTime();
            Eksperyment.aList.remove(Eksperyment.aList.size() / 2);
            endTime = System.nanoTime();
            resultArray = endTime - startTime;

            startTime = System.nanoTime();
            Eksperyment.lList.remove(Eksperyment.lList.size() / 2);
            endTime = System.nanoTime();
            resultLinked = endTime - startTime;
            info.setText("Usunołem element ze środka obu list.");
        }
        if (radio6.isSelected()) {
            startTime = System.nanoTime();
            Eksperyment.aList.remove(Eksperyment.aList.size() - 1);
            endTime = System.nanoTime();
            resultArray = endTime - startTime;

            startTime = System.nanoTime();
            Eksperyment.lList.remove(Eksperyment.lList.size() - 1);
            endTime = System.nanoTime();
            resultLinked = endTime - startTime;
            info.setText("Usunołem element z końca obu list.");
        }
        if (radio7.isSelected()) {
            startTime = System.nanoTime();
            Eksperyment.aList.get(0);
            endTime = System.nanoTime();
            resultArray = endTime - startTime;

            startTime = System.nanoTime();
            Eksperyment.lList.get(0);
            endTime = System.nanoTime();
            resultLinked = endTime - startTime;
            info.setText("Pobrałem wartość z początku obu list.");
        }
        if (radio8.isSelected()) {
            startTime = System.nanoTime();
            Eksperyment.aList.get(Eksperyment.aList.size() / 2);
            endTime = System.nanoTime();
            resultArray = endTime - startTime;

            startTime = System.nanoTime();
            Eksperyment.lList.get(Eksperyment.lList.size() / 2);
            endTime = System.nanoTime();
            resultLinked = endTime - startTime;
            info.setText("Pobrałem wartości ze srodka obu list.");
        }
        if (radio9.isSelected()) {
            startTime = System.nanoTime();
            Eksperyment.aList.get(Eksperyment.aList.size() - 1);
            endTime = System.nanoTime();
            resultArray = endTime - startTime;

            startTime = System.nanoTime();
            Eksperyment.lList.get(Eksperyment.lList.size() - 1);
            endTime = System.nanoTime();
            resultLinked = endTime - startTime;
            info.setText("Usunąłem wartość z końca obu list.");
        }

        if (resultArray > resultLinked) {
            info.setText(info.getText() + "\nArray List: " + resultArray + "\nLinkedList: " + resultLinked + "\nSzybszy był LinkedList o:" + (resultArray - resultLinked));
        }
        if (resultArray < resultLinked) {
            info.setText(info.getText() + "\nArray List: " + resultArray + "\nLinkedList: " + resultLinked + "\nSzybszy był ArrayList o:" + (resultLinked - resultArray));
        }
        if(resultArray == resultLinked){
            info.setText(info.getText() + "\nArray List: " + resultArray + "\nLinkedList: " + resultLinked + "\nRemis!");
        }
    }//GEN-LAST:event_arrayButtonMousePressed

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        Eksperyment.aList.clear();
        Eksperyment.lList.clear();
        for (int i = 0; i <= 1000; i++) {
            Eksperyment.aList.add(String.valueOf(i));
            Eksperyment.lList.add(String.valueOf(i));
        }

        info.setText("Zresetowałem obie listy\nTeraz mają po 10 000 elementów");
    }//GEN-LAST:event_jButton3MousePressed

    private void radio6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Okno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arrayButton;
    private javax.swing.JTextArea info;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radio1;
    private javax.swing.JRadioButton radio2;
    private javax.swing.JRadioButton radio3;
    private javax.swing.JRadioButton radio4;
    private javax.swing.JRadioButton radio5;
    private javax.swing.JRadioButton radio6;
    private javax.swing.JRadioButton radio7;
    private javax.swing.JRadioButton radio8;
    private javax.swing.JRadioButton radio9;
    // End of variables declaration//GEN-END:variables

}
