/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analizaznakow;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import static java.lang.System.exit;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import javax.swing.JFileChooser;

/**
 *
 * @author Tomasz
 */
public class Okno extends javax.swing.JFrame {

    HashMap<Character, Integer> hmap = new HashMap<Character, Integer>();
    boolean czy = false;

    /**
     * Creates new form Okno
     */
    public Okno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        otworz = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pole = new javax.swing.JTextArea();
        zakoncz = new javax.swing.JButton();
        zlicz = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(500, 300));
        setMinimumSize(new java.awt.Dimension(500, 300));
        setPreferredSize(new java.awt.Dimension(500, 300));
        setResizable(false);

        jLabel1.setText("Analiza tekstu");

        otworz.setText("Otwórz");
        otworz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                otworzMousePressed(evt);
            }
        });

        pole.setEditable(false);
        pole.setColumns(20);
        pole.setRows(5);
        jScrollPane1.setViewportView(pole);

        zakoncz.setText("Zakończ");
        zakoncz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                zakonczMousePressed(evt);
            }
        });

        zlicz.setText("Zlicz znaki");
        zlicz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                zliczMousePressed(evt);
            }
        });

        jButton1.setText("Wyczyść");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel1)
                .addContainerGap(220, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(zlicz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(otworz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zakoncz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(otworz)
                        .addGap(18, 18, 18)
                        .addComponent(zlicz)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(zakoncz)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void otworzMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_otworzMousePressed
        czy = false;
        JFileChooser fc = new JFileChooser();
        String linia = "";
        fc.showOpenDialog(otworz);
        File plik = fc.getSelectedFile();
        String path = plik.getAbsolutePath();
        int count = 0;

        int liczbaLinii = 0;
        try {
            czy = true;
            pole.setText("");
            BufferedReader br = new BufferedReader(new FileReader(path));
            while ((linia = br.readLine()) != null) {
                liczbaLinii++;
            }
            br.close();
            BufferedReader br2 = new BufferedReader(new FileReader(path));
            System.out.println(liczbaLinii);
            String[] tab = new String[liczbaLinii];
            for (int i = 0; i < liczbaLinii; i++) {
                tab[i] = br2.readLine();
                for (int j = 0; j < tab[i].length(); j++) {
                    if (!hmap.containsKey(tab[i].charAt(j))) {
                        System.out.println(tab[i].charAt(j));
                        hmap.put(tab[i].charAt(j), 1);
                    } else {
                        count = hmap.get(tab[i].charAt(j));
                        hmap.put(tab[i].charAt(j), count + 1);
                    }
                }

            }

            for (int i = 0; i < tab.length; i++) {
                pole.setText(pole.getText() + tab[i] + "\n");
            }
            br2.close();

        } catch (Exception e) {
            e.printStackTrace();

        }

    }//GEN-LAST:event_otworzMousePressed

    private void zakonczMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zakonczMousePressed
        exit(0);
    }//GEN-LAST:event_zakonczMousePressed

    private void zliczMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zliczMousePressed
        if (czy) {
            pole.setText("");
            Set set = hmap.entrySet();
            Iterator iterator = set.iterator();
            while (iterator.hasNext()) {
                Map.Entry mapka = (Map.Entry) iterator.next();
                pole.setText(pole.getText() + mapka.getKey() + " : " + mapka.getValue() + " wystąpień" + "\n");
                System.out.print("key is: " + mapka.getKey() + " & Value is: ");
                System.out.println(mapka.getValue());
            }
        } else {
            pole.setText("Nie załadowałeś pliku");
        }

    }//GEN-LAST:event_zliczMousePressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        czy = false;
        pole.setText("");
    }//GEN-LAST:event_jButton1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Okno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton otworz;
    private javax.swing.JTextArea pole;
    private javax.swing.JButton zakoncz;
    private javax.swing.JButton zlicz;
    // End of variables declaration//GEN-END:variables
}
